### ISSUE TITLE
Fan Wiring

### ISSUE THREAD

**Issue by rrik** [pila81/Trident_Mods#1]
What is the extrusion mount that you are connecting the fan wiring to? Is this with a 2x2 molex?

**Comment by pila81** [comment]
My fan wires are crimped together in the microfit pins so I'm using a 1x2 microfit plug.  
The extrusion mount is a modified version of samwiseg0's Microfit AB Plug (which is derived from Ramalama2's AB Motor Plug).  
I've added it to my repo for your convenience: https://github.com/pila81/Trident_Mods/tree/main/Microfit_2020_Mount_1x2  
There are links to the original designs in there.
