### ISSUE TITLE
Question: Z Carriages FLEX - Nut Mount?

### ISSUE THREAD

**Issue by JanB97** [pila81/Trident_Mods#2]
I would like to try your bed mount, but I am not sure how the cariage is mounted to the leadscrew.
Do you put heatset inserts and use m3 screws? also does the spacer go between cariage and nut?

**Comment by pila81** [comment]
Yes, 2 heatset inserts go into the bottom of each carriage. The leadscrew nut is attached with M3 screws (8mm I think) with the spacer in between.

**Comment by JanB97** [comment]
Thank you!
